apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: ai-devops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      serviceAccountName: backend-sa

      containers:
        - name: ai-devops-backend
          image: itsharshpaliwal/ai-devops-backend:3.1
          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 8000

          env:
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: auth-secrets
                  key: JWT_SECRET

            - name: OPENROUTER_API_KEY
              valueFrom:
                secretKeyRef:
                  name: ai-devops-secrets
                  key: OPENROUTER_API_KEY

            - name: DATABASE_URL
              value: postgresql+psycopg2://ai_devops:change-this-password@postgres:5432/ai_devops

          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3

          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 20
            timeoutSeconds: 3
            failureThreshold: 3

---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: ai-devops
spec:
  selector:
    app: backend
  ports:
    - port: 8000
      targetPort: 8000
  type: NodePort
